# https://taskfile.dev

version: '3'

vars:
  APP_NAME: sda

tasks:
  build:
    cmds:
      - cmd: go build -o {{.APP_NAME}}-windows.exe
        desc: Build the application
        silent: true
        platforms: [windows]
      - cmd: env GOOS=linux GOARCH=amd64 go build -o {{.APP_NAME}}
        desc: Build the application
        silent: true
        platforms: [linux, darwin]

  crossbuild:
    desc: Build for all platforms
    cmds:
      - task: build_for_windows_amd64
      - task: build_for_windows_arm64
      - task: build_for_linux_amd64
      - task: build_for_linux_arm64

  build_for_windows_amd64:
    cmds:
      - echo "Building for $GOOS-$GOARCH"
      - go build -o target/{{.APP_NAME}}-$GOOS-$GOARCH.exe
    env:
      GOOS: windows
      GOARCH: amd64
    silent: true

  build_for_windows_arm64:
    cmds:
      - echo "Building for $GOOS-$GOARCH"
      - go build -o target/{{.APP_NAME}}-$GOOS-$GOARCH.exe
    env:
      GOOS: windows
      GOARCH: arm64
    silent: true

  build_for_linux_amd64:
    cmds:
      - echo "Building for $GOOS-$GOARCH"
      - go build -o target/{{.APP_NAME}}-$GOOS-$GOARCH
    env:
      GOOS: linux
      GOARCH: amd64
    silent: true

  build_for_linux_arm64:
    cmds:
      - echo "Building for $GOOS-$GOARCH"
      - cmd: go build -o target/{{.APP_NAME}}-$GOOS-$GOARCH
    env:
      GOOS: linux
      GOARCH: arm64
    silent: true

  clean:
    desc: Clean the project
    cmds:
      - cmd: rm -rf target
        platforms: [linux, darwin]
      - cmd: pwsh -c "if (Test-Path target) {Remove-Item -Recurse target}"
        platforms: [windows]
      - go clean