name: manual

on: workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Setup Just
        uses: extractions/setup-just@v2

      - name: Build
        run: just build

      - name: Test
        run: just test
